import { Inter } from 'next/font/google'
import './globals.scss'
import Counter from './counter';
import { Header } from "@/components/Header";

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  // title: 'Create Next App Router',
  title: {
    default: 'Create Next App',
    template: `%s | Next App`,
  },
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="ja">
      <body className={inter.className} id='root'>
        <Header />
        {children}
        <Counter />
      </body>
    </html>
  )
}
